{% set name = "ypy_websocket" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|replace("_", "-" ) }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43a001473f5c8abcf182f603049cf305cbc855ad8deaa9dfa0f3b5a7cea9d0ff

build:
  number: 0
  skip: true # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - hatchling
    - pip
    - python
    - wheel
  run:
    - aiofiles >=22.1.0,<23
    - aiosqlite >=0.17.0,<1
    - python
    - y-py >=0.6.0,<0.7.0

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
  imports:
    - ypy_websocket
  commands:
    - pip check
    - cd tests && npm install
    - cd .. && pytest -vv --asyncio-mode=auto --ignore tests/test_ypy_yjs.py

about:
  home: https://github.com/y-crdt/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy
  description: ypy-websocket is an async WebSocket connector for Ypy.
  dev_url: https://github.com/y-crdt/ypy-websocket
  doc_url: https://github.com/y-crdt/ypy-websocket/blob/main/README.md

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
