{% set name = "ypy-websocket" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/ypy_websocket/ypy_websocket-{{ version }}.tar.gz
  sha256: 2e7e114e8060fb2f8e1e1e8308e936ec56764df5a5a8b9562cae3a63b9ad186e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - y-py >=0.5.3,<0.6.0
    - aiofiles >=0.8.0,<1
    - aiosqlite >=0.17.0,<1

test:
  imports:
    - ypy_websocket

about:
  home: https://github.com/y-crdt/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy
  dev_url: https://github.com/y-crdt/ypy-websocket

extra:
  recipe-maintainers:
    - davidbrochart
