{% set name = "ypy-websocket" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/ypy_websocket/ypy_websocket-{{ version }}.tar.gz
  sha256: a1aee9a5c483d306e5ba5d7ccab3c9412264d4ee681fd2e456071f82dac1a0a6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - y-py >=0.4.4

test:
  imports:
    - ypy_websocket

about:
  home: https://github.com/davidbrochart/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy
  dev_url: https://github.com/davidbrochart/ypy-websocket

extra:
  recipe-maintainers:
    - davidbrochart
